[package]
name = "snow-config"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
miniz_oxide = { version = "0.9", default-features = false, features = ["with-alloc"] }
serde_json = "1"
snow-app-core = { path = "../snow-app-core" }
snow-net = { path = "../snow-net" }

[lints]
workspace = true
