[package]
name = "snow-canvas-text"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
unicode-segmentation = "1.13"
unicode-width = "0.2"
serde = { version = "1.0", features = ["derive"] }
snow-ui-shell = { path = "../snow-ui/snow-ui-shell" }
