//! 旧版能力清单的 Rust 镜像（由 `snow_shot/mcp-capabilities.json` 生成；一致性由测试对照）。

use crate::registry::Domain;

/// 全部 tool 名，按旧清单的域与顺序排列：`(域, 名称)`。
pub const MANIFEST: &[(Domain, &str)] = &[
    (Domain::Screenshot, "snow_shot_mcp_status"),
    (Domain::Screenshot, "snow_shot_screenshot_begin"),
    (Domain::Screenshot, "snow_shot_screenshot_state"),
    (Domain::Screenshot, "snow_shot_screenshot_set_selection"),
    (Domain::Screenshot, "snow_shot_screenshot_set_tool"),
    (Domain::Screenshot, "snow_shot_screenshot_apply_annotations"),
    (Domain::Screenshot, "snow_shot_screenshot_undo"),
    (Domain::Screenshot, "snow_shot_screenshot_redo"),
    (Domain::Screenshot, "snow_shot_screenshot_render"),
    (Domain::Screenshot, "snow_shot_screenshot_save"),
    (Domain::Screenshot, "snow_shot_screenshot_copy"),
    (Domain::Screenshot, "snow_shot_screenshot_pin"),
    (Domain::Screenshot, "snow_shot_screenshot_finish"),
    (Domain::Screenshot, "snow_shot_screenshot_cancel"),
    (Domain::Screenshot, "snow_shot_screenshot_direct_capture"),
    (
        Domain::Screenshot,
        "snow_shot_screenshot_set_selection_style",
    ),
    (Domain::Screenshot, "snow_shot_screenshot_set_tool_style"),
    (Domain::Screenshot, "snow_shot_screenshot_edit_elements"),
    (Domain::Screenshot, "snow_shot_screenshot_recapture"),
    (Domain::Screenshot, "snow_shot_screenshot_scrolling"),
    (Domain::Screenshot, "snow_shot_screenshot_scroll_once"),
    (Domain::Screenshot, "snow_shot_screenshot_recognize"),
    (Domain::Screenshot, "snow_shot_screenshot_translate"),
    (Domain::Screenshot, "snow_shot_screenshot_auto_filter"),
    (Domain::Screenshot, "snow_shot_screenshot_operation"),
    (Domain::Screenshot, "snow_shot_screenshot_edit_recognition"),
    (
        Domain::Screenshot,
        "snow_shot_screenshot_export_recognition",
    ),
    (Domain::Screenshot, "snow_shot_screenshot_draw_template"),
    (Domain::Application, "snow_shot_app_status"),
    (Domain::Application, "snow_shot_app_displays"),
    (Domain::Application, "snow_shot_app_action"),
    (Domain::Application, "snow_shot_settings_get"),
    (Domain::Application, "snow_shot_settings_update"),
    (Domain::Application, "snow_shot_settings_reset"),
    (Domain::Application, "snow_shot_settings_action"),
    (Domain::Application, "snow_shot_models_list"),
    (Domain::Application, "snow_shot_models_update"),
    (Domain::Application, "snow_shot_credentials_set"),
    (Domain::Application, "snow_shot_history_list"),
    (Domain::Application, "snow_shot_history_get"),
    (Domain::Application, "snow_shot_history_delete"),
    (Domain::Application, "snow_shot_history_clear"),
    (Domain::Application, "snow_shot_history_action"),
    (Domain::Application, "snow_shot_configuration_export"),
    (Domain::Application, "snow_shot_configuration_import"),
    (Domain::Application, "snow_shot_storage_status"),
    (Domain::Application, "snow_shot_storage_cleanup"),
    (Domain::Application, "snow_shot_permissions_get"),
    (Domain::Application, "snow_shot_permissions_request"),
    (Domain::Application, "snow_shot_updates_status"),
    (Domain::Application, "snow_shot_updates_action"),
    (Domain::Application, "snow_shot_templates_list"),
    (Domain::Application, "snow_shot_templates_update"),
    (Domain::Application, "snow_shot_translation_catalog"),
    (Domain::Application, "snow_shot_translation_start"),
    (Domain::DocumentsJobs, "snow_shot_document_open"),
    (Domain::DocumentsJobs, "snow_shot_document_list"),
    (Domain::DocumentsJobs, "snow_shot_document_state"),
    (Domain::DocumentsJobs, "snow_shot_document_clone"),
    (
        Domain::DocumentsJobs,
        "snow_shot_document_apply_annotations",
    ),
    (Domain::DocumentsJobs, "snow_shot_document_set_selection"),
    (Domain::DocumentsJobs, "snow_shot_document_undo"),
    (Domain::DocumentsJobs, "snow_shot_document_redo"),
    (Domain::DocumentsJobs, "snow_shot_document_render"),
    (Domain::DocumentsJobs, "snow_shot_document_save"),
    (Domain::DocumentsJobs, "snow_shot_document_copy"),
    (Domain::DocumentsJobs, "snow_shot_document_pin"),
    (
        Domain::DocumentsJobs,
        "snow_shot_document_set_selection_style",
    ),
    (Domain::DocumentsJobs, "snow_shot_document_close"),
    (Domain::DocumentsJobs, "snow_shot_document_recognize"),
    (Domain::DocumentsJobs, "snow_shot_document_present"),
    (Domain::DocumentsJobs, "snow_shot_document_set_tool"),
    (Domain::DocumentsJobs, "snow_shot_document_set_tool_style"),
    (Domain::DocumentsJobs, "snow_shot_document_edit_elements"),
    (Domain::DocumentsJobs, "snow_shot_document_draw_template"),
    (Domain::DocumentsJobs, "snow_shot_document_sample_color"),
    (Domain::DocumentsJobs, "snow_shot_document_recapture"),
    (
        Domain::DocumentsJobs,
        "snow_shot_document_recognition_state",
    ),
    (Domain::DocumentsJobs, "snow_shot_document_edit_recognition"),
    (
        Domain::DocumentsJobs,
        "snow_shot_document_export_recognition",
    ),
    (Domain::DocumentsJobs, "snow_shot_document_original_content"),
    (Domain::DocumentsJobs, "snow_shot_document_auto_filter"),
    (Domain::DocumentsJobs, "snow_shot_job_get"),
    (Domain::DocumentsJobs, "snow_shot_job_list"),
    (Domain::DocumentsJobs, "snow_shot_job_cancel"),
    (Domain::DocumentsJobs, "snow_shot_artifact_list"),
    (Domain::DocumentsJobs, "snow_shot_artifact_read"),
    (Domain::DocumentsJobs, "snow_shot_artifact_release"),
    (Domain::RecordingPinned, "snow_shot_recording_state"),
    (Domain::RecordingPinned, "snow_shot_recording_start"),
    (Domain::RecordingPinned, "snow_shot_recording_control"),
    (Domain::RecordingPinned, "snow_shot_pinned_list"),
    (Domain::RecordingPinned, "snow_shot_pinned_get"),
    (Domain::RecordingPinned, "snow_shot_pinned_create"),
    (Domain::RecordingPinned, "snow_shot_pinned_replace"),
    (Domain::RecordingPinned, "snow_shot_pinned_update"),
    (Domain::RecordingPinned, "snow_shot_pinned_action"),
    (Domain::RecordingPinned, "snow_shot_pinned_export"),
    (Domain::RecordingPinned, "snow_shot_pinned_edit"),
    (Domain::RecordingPinned, "snow_shot_group_list"),
    (Domain::RecordingPinned, "snow_shot_group_update"),
];
